---
editor_options: 
  markdown: 
    wrap: sentence
---
 
## Harvest recommendations

> Operational Update: The description of Amendment 56 specifications for POP and details regarding the development of the Risk Table have been truncated to provide minimal background and highlight relevant updates or changes made for this cycle. The reader is referred to the last full assessment (Hulson et al., 2021) for the entirety of this section, including details on the projection approach.

### Amendment 56 Reference Points

POP in the GOA are managed under Tier 3 of Amendment 56. It is assumed that the equilibrium level of recruitment is equal to the average of age-2 recruitments between 1979 and `r year-2` (i.e., the 1977-`r year-4` year classes). The most recent two years of recruitment are not included in the projection due to uncertainty. This definition of equilibrium recruitment is used to estimate the  $B_{40\%}$ reference point. Other useful biomass reference points which can be calculated using this assumption are $B_{100\%}$ and $B_{35\%}$, defined analogously to $B_{40\%}$.

Female spawning biomass for `r year+1` is estimated at 216,635 t. This is above  $B_{40\%}$=132,767 t. Under Amendment 56, Tier 3, the maximum permissible fishing mortality for ABC is $F_{40\%}$ and fishing mortality for OFL is $F_{35\%}$. The `r year+1` estimates of biomass-based reference points, and the resultant ABC and OFL based on the fishing mortality rates are:

| Reference Point | Description                                                                                                                                                | Value   |
|------------------------|------------------------|------------------------|
| $B_{100\%}$      | The equilibrium spawning biomass that would be obtained in the absence of fishing                                                                          | 331,917 t |
| $B_{40\%}$       | 40% of the equilibrium spawning biomass that would be obtained in the absence of fishing                                                                   | 132,767 t |
| $B_{35\%}$       | 35% of the equilibrium spawning biomass that would be obtained in the absence of fishing                                                                   | 116,171 t |
| $F_{40\%}$       | The fishing mortality rate that reduces the equilibrium level of spawning per recruit to 40% of the level that would be obtained in the absence of fishing | 0.10    |
| ABC             | Yield at $F_{40\%}$ in 2024                                                                                                                                       | 38,268 t |
| $F_{35\%}$       | The fishing mortality rate that reduces the equilibrium level of spawning per recruit to 35% of the level that would be obtained in the absence of fishing | 0.12    |
| OFL             | Yield at $F_{35\%}$  in 2024                                                                                                                                       | 45,580 t  |


### Specification of OFL and Maximum Permissible ABC {#oflabc}

#### Standard Harvest Scenarios (Harvest Projections) {#harvestprojections}

A standard set of projections is required for each stock managed under Tier 3 of Amendment 56. This set of projections encompasses seven harvest scenarios designed to satisfy the requirements of Amendment 56, the National Environmental Policy Act, and the Magnuson-Stevens Fishery Conservation and Management Act (MSFCMA). They are as follows; the modifications made for the present assessment are indicated where appropriate.

The first five scenarios are designed to provide a range of harvest alternatives that are likely to bracket the final TAC for `r year`, are as follow (“max$F_{ABC}$” refers to the maximum permissible value of $F_{ABC}$ under Amendment 56):

+   *Scenario 1*:  In all future years, $F$ is set equal to max$F_{ABC}$ (Rationale:  Historically, TAC has been constrained by ABC, so this scenario provides a likely upper limit on future TACs.)

+   *Scenario 2*:  In `r year` and `r year+1`, $F$ is set equal to a constant fraction of max $F_{ABC}$, where this fraction is equal to the ratio of the realized catches in `r paste0(range(year-3, year-1), collapse='-')` to the ABC (which is generally the same s the TAC) recommended in the assessment for each of those years. For the remainder of the future years, maximum permissible ABC is used. (Rationale:  Using recent catch to ABC ratios will yield more realistic projections for the POP fishery, which rarely realizes its full TAC or ABC.) Detail on the exact calculation of these values is shown [below](#authorsF).

+   *Scenario 3*:  In all future years, $F$ is set equal to 50% of max $F_{ABC}$. (Rationale:  This scenario provides a likely lower bound on $F_{ABC}$ that still allows future harvest rates to be adjusted downward when stocks fall below reference levels.)

+   *Scenario 4*:  In all future years, $F$ is set equal to the 2015-2019 average F. (Rationale:  For some stocks, TAC can be well below ABC, and recent average $F$ may provide a better indicator of FTAC than $F_{ABC}$.)

+   *Scenario 5*:  In all future years, $F$ is set equal to zero. (Rationale:  In extreme cases, TAC may be set at a level close to zero.)

In addition to the seven standard harvest scenarios, Amendments 48/48 to the BSAI and GOA Groundfish Fishery Management Plans require projections of the likely OFL two years into the future. These are needed to satisfy the MSFCMA’s requirement to determine whether a stock is currently in an overfished condition or is approaching an overfished condition. These two scenarios are as follows (for Tier 3 stocks, the MSY level is defined as $B_{35\%}$):

+   *Scenario 6*:  In all future years, $F$ is set equal to FOFL. (Rationale:  This scenario determines whether a stock is overfished. If the stock is expected to be above 1) above its MSY level in `r year` or 2) above ½ of its MSY level in  `r year` and above its MSY level in  `r year+10` under this scenario, then the stock is not overfished.) While Scenario 6 gives the best estimate of OFL for `r year`, it does not provide the best estimate of OFL for `r year + 1`, because the mean `r year` catch under Scenario 6 is predicated on the `r year` catch being equal to the `r year` OFL, whereas the actual `r year` catch will likely be less than the `r year` OFL.
The executive summary contains the appropriate one- and two-year ahead projections for both ABC and OFL.

+   *Scenario 7*:  In `r year` and `r year+1`, $F$ is set equal to max$F_{ABC}$, and in all subsequent years $F$ is set equal to $F_{OFL}$ .(Rationale: This scenario determines whether a stock is approaching an overfished condition. If the stock is 1) above its MSY level in `r year+1` or 2) above 1/2 of its *MSY* level in `r year+1` and expected to be above its MSY level in `r year+13` under this scenario, then the stock is not approaching an overfished condition.)


#### How Future Catches are Specified for Scenario 2 (Author's F) {#authorsF}

> The method for specifying catches in years `r year` to `r year+2` has not changed from the 2021 assessment. 

For Scenario 2 (Author's *F*); we use pre-specified catches to increase accuracy of short-term projections in fisheries where the catch is usually less than the ABC. This was suggested to help management with setting preliminary ABCs and OFLs for two-year ahead specifications.

The method to calculate catches for this scenario is as follows:
  1. In-year catches are defined as the actual observed catch through ~October 1, plus the average catch taken between October 1 and December 31 of the previous three years (`r year-3` to `r year-1`). The expansion factor for the observed catch through `r year` is 1.17; the estimated in-year catch for `r year` is `r prettyNum(c1,big.mark=',')` t.
  2. For `r year+1` and `r year+2`, predicted catch is given by the ratio of the lass three catches to their respective TACs, multiplied by the TACs in future year $y^{*}$ given above (which are generally the same as the ABCs): $\langle \sum_{y-3}^{y-1}\frac{C_y}{TAC_y} \rangle TAC_{y^*}$. The average catch to TAC ratio in the previous three years was 0.79; predicted catches for `r year+1` and `r year+2` are `r prettyNum(c2,big.mark=',')` t and `r prettyNum(c3,big.mark=',')` t, respectively.

Projected catches, spawning biomass, and fishing mortality rates corresponding to the alternative harvest scenarios over a 13-year period are shown in Tables \@ref(tab:projections_catches) through \@ref(tab:projections_f).


During the 2006 CIE review, it was suggested that projections should account for uncertainty in the entire assessment, not just recruitment from the endpoint of the assessment. We continue to present an alternative projection scenario using the uncertainty of the full assessment model, harvesting at the same estimated yield ratio as Scenario 2, except for all years instead of the next two. This projection propagates uncertainty throughout the entire assessment procedure based on MCMC. The projection shows wide credibility intervals on future spawning biomass (Figure 9-17). The $B_{35\%}$ and $B_{40\%}$  reference points and future recruitment are based on the 1979-`r year-2` age-2 recruitments, and this projection predicts that the median spawning biomass will eventually tend toward these reference points while at harvesting at $F_{40\%}$ . 
During the 2006 CIE review, it was suggested that projections should account for uncertainty in the entire assessment, not just recruitment from the endpoint of the assessment. We continue to present an alternative projection scenario using the uncertainty of the full assessment model, harvesting at the same estimated yield ratio as Scenario 2, except for all years instead of the next two.
This projection propagates uncertainty throughout the entire assessment procedure based on MCMC.
The projection shows wide credibility intervals on future spawning biomass (Figure 10.\@ref(fig:ssbproj)).
The $B_{35\%}$ and $B_{40\%}$ reference points and future recruitment is based on the 1979-2019 age-2 recruitment, and this projection predicts that the median spawning biomass will eventually tend toward these reference points while at harvesting at $F_{40\%}$.

## Risk Table and ABC recommendation {#risktable}

The SSC in its December 2018 minutes recommended that all assessment authors use the risk table when determining whether to recommend an ABC lower than the maximum permissible.
The risk table template and examples of concerns for each level are provided in the most recent full assessment; the risk table scoring for POP has not changed since 2021:

```{r}
l1 = "Level 1: No increased concerns"
l2 = "Level 2: Substantially increased concerns"
l3 = "Level 3: Major concern"
l4 = "Level 4: Extreme concern"
require(flextable)
data.frame(assess = l2,
           pop = l2,
           enviro = l1,
           fish = l1) %>% 
  flextable() %>% 
    width(j = ~ assess, width = 1.5) %>% 
    width(j = ~ pop, width = 1.5) %>% 
    width(j = ~ enviro, width = 1.5) %>% 
    width(j = ~ fish, width = 1.5) %>% 
    flextable::set_header_labels(level = "",
                    assess = "Assessment-related considerations",
                    pop = "Population dynamics considerations",
                    enviro = "Environmental/ecosystem considerations",
                    fish = "Fishery Performance") %>% 
  flextable::fontsize(size = 10) %>% 
  font(fontname = "Times", part = "all") %>%
    italic(part ='header')
```

An abridged summary of the considerations that led to this determination for each category follows.

### Assessment considerations {#assessmentconsiderations}

The GOA POP assessment model exhibits a negative retrospective pattern (spawning biomass continues to increase with new data).

This is driven by increases in the trawl survey biomass, which has been consistently under-estimated since 2013, and may be suggestive of model-misspecification.
This results in a an "assessment considerations" score of level 2, a substantially increased concern.

### Population dynamics considerations

The model estimates above-average recruitment events in the last three decades to account for the increasing survey biomass observations (Figures 10.\@ref(fig:recruitment) and 10.\@ref(fig:recdevs)).  The estimated recruitment events are still insufficient to satisfactorily fit the recent survey data; these increases are not observed in the early time series nor are they typical for an ecosystem that is warming (with the exception of sablefish). The unusual trend of rapid increases in stock size and recruitment estimates results in a *Level 2 (substantially increased concern) population dynamics rating*.
  
### Environmental/Ecosystem considerations

Ocean thermal conditions have been moderate for adult POP and moderate to below average for larvae. Trends for zooplankton have been mixed. POP are benthic, continental slope (150-300 m depths) dwellers as adults, with a pelagic then inshore benthic juvenile stage (age 1 to 3) in the Gulf of Alaska (GOA) (Carlson and Haight 1976, Love et al. 2002, Rooper and Bolt 2005, Rooper et al. 2007, NPFMC 2010). Spawning occurs during winter and early spring and larvae settle to the benthos within 3-6 months (Love et al. 2002). It is reasonable to expect that the 2021 and predicted 2022 average deeper ocean temperatures will provide good spawning habitat. Average to cooler surface temperatures will contribute to average to below average pelagic conditions for larval rockfish, as warm spring surface waters are conducive to larval survival and positive rockfish recruitment (Moss 2016, Morgan 2019). Ocean temperatures at the surface and at depth on the shelf were around the long-term average in 2021 (AFSC Bottom Trawl Survey, Laman 2021; AFSC EcoFOCI survey, Rogers et al 2021; Seward Line Survey, Danielson 2021), although western GOA started the year with warmer surface waters (satellite data; Watson 2021) and there was slightly above average warmth (5.2 °C) at 200m depth along the outer edge of the shelf during the summer (AFSC Longline Survey; Siwicke 2021). This is within the range of preferred ocean temperatures for adults (4.0-6.5 °C, Major and Shippen 1970). Numerous temperature time series showed signs of cooling from previous surveys (returning to average from recent marine heatwave years 2014-2016, 2019) at the surface and at depth, and 2022 surface temperatures are predicted to continue cooling, in alignment with La Niña conditions and a negative Pacific Decadal Oscillation.

Potential competition levels with juvenile sablefish and pink salmon are unknown. Planktivorous foraging conditions were moderate and regionally variable across the GOA in 2021. The primary prey of the adult Pacific Ocean Perch include calanoid copepods, euphausiids, myctophids, and miscellaneous prey in the GOA (Byerly 2001, Yang and Nelson 2000, Yang 2003). While zooplankton trends were variable, an important observation shows continued decline in POP body condition (i.e. lower weights at length) since 2015 (Bottom Trawl Survey, O'Leary, 2021).Declines are especially pronounced in SEAK and Yakutat regions since the previous survey in 2019. The timing of this declining trend matches the time frame of increasing POP population since the 2014-2016 marine heatwave.

Regionally, zooplankton trends varied from the western to eastern GOA.
The western GOA had lower spring biomass of large copepods and approximately average biomass of smaller copepods was around Kodiak, characteristics of previous warm, less productive years (e.g., 2019). Planktivorous seabird reproductive success, an indicator of zooplankton availability and nutritional quality, was below average just north of Kodiak (E. Amatuli Island; Drummond and Renner 2021). Around the eastern edge of WGOA (Seward Line, Middleton Island) the biomass of large copepods was average to above-average (Seward Line Survey, Hopcroft 2021) and planktivorous seabirds had better reproductive success (Middleton Island, Hatch et al. 2021), indicating improved forage conditions. The eastern GOA inside waters of Icy Strait, northern southeast Alaska, had higher than average large copepods and euphausiids (AFSC SECM Survey, Icy Strait, Fergusson 2021), however planktivorous seabirds had mixed reproductive success.

Potential competitors are large year classes of juvenile sablefish (2016, 2018) and a pink salmon which are returning in very high numbers this year (Murphy et al. 2021, Shaul et al. 2021). Predators of juvenile POP include Pacific halibut, arrowtooth flounder, seabirds, rockfish, salmon, and lingcod (Moss 2016, Hulson et al. 2020).  Predators of adults include Pacific halibut, sablefish, and sperm whales (Moss 2016, Hulson et al. 2020). Halibut and arrowtooth flounder populations remain low relative to previous levels, and, in general, there is no cause to suspect increased predation pressure on larval or adult demersal shelf rockfish.

*Environmental and ecosystem effects for POP are scored as Level 1 (normal concern)*.
 

### Fishery performance

The fishery CPUE shows consistent patterns in abundance similar to the bottom trawl survey and there have been no recent changes to spatial distribution of catch, percent of TAC taken, or fishing duration. There are no indications of adverse signals or concerns about the fishery in terms of resource-use, performance, or behavior. We will continue to monitor the fishery performance as it pertains to the COVID-19 pandemic.

*Fishery Performance for POP is scored as Level 1 (normal concern)*.
 
### Risk Table Summary and ABC recommendation
 
*We do not recommend a reduction in ABC because the retrospective pattern in this assessment indicates an increasing population abundance.* We acknowledge that the current assessment model does not appropriately explain these dynamics at present.

### Area Allocation of Harvests {#apportionment}

#### Overview

Apportionment of ABC and OFL among regulatory areas uses the random effects model ("REMA" version `0.1.0`) developed by the survey averaging working group. This model estimates random effects parameters that control the variation of estimated biomass across years and areas, and is fit to the trawl survey biomass estimates (with associated variance) for the Western, Central, and Eastern GOA. The REMA model fits the survey data in each area well (Figure 10.\@ref(fig:rema)). Both the observations and predictions indicate that most biomass is in the Central Gulf; biomass has increased in the Central and Western Gulf, and decreased in the Eastern Gulf. The estimated apportionment among areas are as follows: 6.8% for the Western area (up from 4.6% in 2019), 80.5% for the Central area (up from 75.8% in 2019), and 12.7% for the Eastern area (down from 19.6% in 2019). This corresponds to recommended ABC's of 2,602 t for the Western area, 30,806 t for the Central area, and 4,860 t for the Eastern area.


#### Amendment 41 Downscaling

The Eastern gulf is comprised of two sub-areas for apportionment purposes: the area west of $140^{\circ}W$ longitude ("West Yakutat") and the area east and southeast of $140^{\circ}W$ longitude ("East Yakutat and Southeast Outside"). Amendment 41 prohibited trawling in the latter area, so we re-calculate apportionment rates for the Eastern Gulf to consider the ratio of biomass both within and outside of the closed area. This re-calculation is obtained by:

  1. Taking the ratio of estimated biomass between the open and closed area (W. Yakutat versus E. Yakutat/SEO). The ratio for `r year` using biomass from `r paste0(seq(year-4,year,2),collapse = ', ')` is XX, up/down from the ratio of 0.29 used in `r year-2`. 
  
  2.  Pete to help clarify: This calculation was based on the team's previous recommendation that we use the weighted average of the upper 95% confidence interval for the W.
Yakutat. We computed this interval this year using the weighted average of the ratio for 2019, 2021 and 2023. We calculated the approximate upper 95% confidence interval using the variance of a weighted mean for the 2017-2021 weighed mean ratio. 

Applying the biomass ratio to the [ABC](#oflabc) for the Eastern Gulf results in an ABC apportionment of 1,409 t to the W. Yakutat area, with 3,451 t unharvested in the E. Yakutat/SEO. The OFL for POP, where $F_{OFL}$ = $F_{35\%}$=0.12), is 45,580. Using the same approach as for ABCs, the OFL for the Western Gulf, Central Gulf, and W. Yakutat^[In 2012, the Plan Team and SSC recommended combined OFLs for the Western, Central, and West Yakutat areas (W/C/WYK) because the original rationale of an overfished stock no longer applied. However, because of concerns over stock structure, the OFL for SEO remained separate to ensure this unharvested OFL was not utilized in another area. The Council adopted these recommendations.] is 41,470 t and 4,110 t in the SEO area. 

### Status Determination

> The status definitions under the MSFCMA have been truncated from this report. The status determinations described below are derived from the offical catch estimates and the `r year` projected spawning biomass under (Harvest Scenarios)[#harvestscenarios] 6 and 7.

#### Overfishing 

The official catch estimate for the most recent complete year (`r year-1`) is `r prettyNum(c0,big.mark=",")` t.
This is less than the `r year-1` OFL of `r prettyNum(45580,big.mark=",")` t. *The stock is not subject to overfishing.*

#### Overfished (Harvest Scenario 6)

The minimum stock size threshold (MSST) for POP is given by the $B_{35\%}$ which is `r prettyNum(b35_23,big.mark=",")` in `r year`. The estimated stock spawning biomass in `r year` is above the MSST at `r prettyNum(ssb_23,big.mark=",")`. *The stock is not overfished*.

#### Approaching Overfished (Harvest Scenario 7)
The mean estimated stock spawning biomass in `r year+2` is above the MSST at 189,598. *The stock is not approaching an overfished state*.

The fishing mortality that would have produced a catch for `r year-1` equal to the `r year-1` OFL is `r best_f`.
