# Appendix 9B.—Summary of the 2021 CIE review of Gulf of Alaska Pacific Ocean perch

The Center for Independent Expert (CIE) review for Gulf of Alaska Pacific ocean perch was conducted virtually from March 30 to April 1, 2021. The panel of experts consisted of Drs Noel Cadigan, Saang-Yoon Hyun, and Geoff Tingley. Overall, the review was productive, resulting in a number of recommendations for future development and research into the assessment for GOA POP. By the conclusion of the review the experts found the assessment to be of high quality, and the reviews contained statements like, “The overall outcome of this assessment, as reviewed, is that it meets the description of best available science and exceeds the acceptability quality threshold to be used to inform management.” (Tingley).
Each of the reviewers provided research recommendations that should serve to improve the assessment model for GOA POP. A number of the recommendations focused on a variety of sensitivity analyses, while others involved more in-depth model development. Distilling these comments, the more in-depth recommendations included:
•	Investigate data weighting of compositional data
•	Develop a state-space model to be run in parallel to the current assessment
•	Continue to investigate use of VAST estimates of survey biomass, in particular investigate reasons behind the divergence between design-based and model-based estimates of abundance
As it pertains to the use of VAST estimates of survey biomass, the consensus among the reviewers was that it is still premature to use this index in the assessment until it can be more thoroughly investigated. This was also the consensus with the use of acoustic survey biomass estimates as an additional index to the model. Due to the recommendations that further work be conducted before implementation into the assessment, and in conjunction with the work that the AFSC internal review team performed through 2020 and 2021 (which additionally identified different methods to estimate fishery selectivity as a topic to be considered in the assessment model development), the GOA POP assessment will not incorporate any substantial model changes for the 2021 assessment cycle, but will investigate and continue to develop these various recommendations to be potentially implemented in the next full assessment that will be conducted in 2023.
The following tables compile the main recommendations suggested by the reviewers and are organized by the terms of reference (TOR) of the review.
