---
bibliography: ["VAST_safe.bib"]   
csl: "fishfish.csl"
---

# Appendix 10d Model Equations

## Population Dynamics

+-------------------------------------------------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| Equation                                                                | Description                                                      | Notation                                                                                                |
+=========================================================================+==================================================================+=========================================================================================================+
| $N_{2,y}=e^{\mu_r+\epsilon_y^r}$                                        | Annual numbers at age of recruitment (age-2)                     | $y$ year, $a$ age $\mu_r$ average recruitment, $\epsilon_y^r$ annual recruitment deviation              |
+-------------------------------------------------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| $N_{ay}=N_{a-1,y-1}e^{-(M+F_{a-1,y-1})}=N_{a-1,y-1}e^{-Z_{a-1,y-1}}$    | Annual numbers at age between recruitment age and plus age group | $M$ natural mortality, $F_{ay}$ annual fishing mortality at age, $Z_{ay}$ annual total mortality at age |
+-------------------------------------------------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| $N_{a^+,y}=N_{a^+-1,y-1}e^{-Z_{a^+-1,y-1}}+N_{a^+,y-1}e^{-Z_{a^+,y-1}}$ | Annual numbers at age in plus group                              | $a^+$ plus group age (29)                                                                               |
+-------------------------------------------------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| $SB_Y=\sum_{a=2}^{a+}w_a\hat m_aN_{ay}$                                 | Annual spawning biomass                                          | $\hat m_a$ maturity at age                                                                              |
+-------------------------------------------------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+
| $\hat m_a = \frac{1}{1+e^{-\delta^m(a-a_{50\%}^m)}}$                    | Maturity at age                                                  | $\delta^m$ logistic slope parameter                                                                     |
|                                                                         |                                                                  |                                                                                                         |
|                                                                         |                                                                  | $a_{50\%}^m$ logistic age at 50% maturity                                                               |
+-------------------------------------------------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+

## Observation Model

+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| Equation                                                                        | Description                                            | Notation                                                                                                             |
+=================================================================================+========================================================+======================================================================================================================+
| $\hat C_y = \sum_{a=2}^{a^+}w_a \frac{N_{ay}F_{ay}(1-e^{-Z_{ay}})}{Z_{ay}}$     | Annual numbers at age of recruitment (age-2)           | $w_a$ weight at age, $s_{ay}^f$ fishery selectivity by age and year                                                  |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $F_{ay}=s^f_{ay}F_y=s^f_{ay}e^{\mu_f+\epsilon_y^f}$                             | Annual fishing mortality                               | $F_y$ annual fishing mortality, $\mu_f$ average fishing mortality, $\epsilon_y^f$ annual fishing mortality deviation |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $S_{a,1961:1976}=\frac{1}{1+e^{-\delta(a-a_{50\%})}}$                           | Logistic fishery selectivity for 1961-1976 time period | $\delta$ logistic slope parameter                                                                                    |
|                                                                                 |                                                        |                                                                                                                      |
|                                                                                 |                                                        | $a_{50\%}$ logistic age at 50\$ selectivity                                                                          |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $\hat I_y=q\sum_{a=2}^{a+}N_{ay}s_aw_a$                                         | Predicted bottom trawl survey biomass index            | $q$ bottom trawl survey catchability, $s_a$ bottom trawl survey selectivity                                          |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $S_{a}=\frac{1}{1+e^{-\delta(a-a_{50\%})}}$                                     | Bottom trawl survey selectivity                        | $\delta^m$ logistic slope parameter                                                                                  |
|                                                                                 |                                                        |                                                                                                                      |
|                                                                                 |                                                        | $a_{50\%}^m$ logistic age at 50\$ maturity                                                                           |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $\hat p_{ay} =T_{a \rightarrow a'} \frac{N_{ay}s_a}{\sum_{a=2}^{a^+}N_{ay}s_a}$ | Predicted bottom trawl survey age composition          | $T_{a \rightarrow a'}$ ageing error matrix                                                                           |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $\hat p_{ay} =T_{a \rightarrow a'} \frac{C_{ay}}{\sum_{a=2}^{a^+}C_{ay}}$       | Predicted fishery age composition                      |                                                                                                                      |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| $\hat p_{Ly} =T_{a \rightarrow l,y} \frac{C_{ly}}{\sum_{l=0}^{l^+}C_{ly}}$      | Predicted fishery length composition                   | $T_{a \rightarrow l,y}$ size-age transition matrix                                                                   |
+---------------------------------------------------------------------------------+--------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+

## Likelihood Components

The $\lambda$ notation indicates the weight assigned to each likelihood component. The value of lambda used is shown in the rightmost column.

+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| Equation                                                                                                | Component                                                                                                 | Notation                                                                                        | Component weight                    |
+=========================================================================================================+===========================================================================================================+=================================================================================================+=====================================+
| $\lambda_{\hat C}\sum_y ln \langle\frac{Cy+1^{-5}}{\hat Cy+1^{-5}}\rangle^2$                            | Catches                                                                                                   |                                                                                                 | 50                                  |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\lambda_{\hat I}\sum_y \frac{1}{2(\frac{\sigma_{I_y}}{I_y})^2}ln \langle\frac{I_y}{\hat I_y}\rangle^2$ | Bottom trawl survey biomass                                                                               | $\sigma_{I_y}$ annual survey sampling error                                                     | 1                                   |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\lambda_{\hat p_a} \langle \sum_Y -n_{ay} \sum_a( \hat p_{ay}+1^{-5})ln(p_{ay}+1^{-5}) \rangle$        | Fishery and bottom trawl survey age composition                                                           | $n_{ay}$ square root of sample size                                                             | 1                                   |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\lambda_{\hat p_l} \langle \sum_Y -n_{ly} \sum_l( \hat p_{ly}+1^{-5})ln(p_{ly}+1^{-5}) \rangle$        | Fishery length composition                                                                                | $n_{ay}$ number of hauls standardized to maximum of 100                                         | 1                                   |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\sum_{DA}Binom(n_{a,D},\hat m_a)+\lambda_m \frac{1}{1+e^{-\delta(a-a_{50\%})}}$                        | Maturity                                                                                                  | $n_{ay}$ number of observations at age by dataset                                               | 1000 (penalty on maturity at age 0) |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\frac{1} {2\sigma_\theta^2} ln \langle\frac{\theta}{\theta_{prior}} \rangle^2$                         | Prior penalty for natural mortality \$M\$, survey catchability $q$ and recruitment variability $\sigma_r$ | $\theta$ parameter estimate, $\sigma_{\theta}^2$ prior uncertainty, $\theta_{prior}$ prior mean | N/A                                 |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\lambda_r\langle \frac{1}{2\sigma_r^2}\sum_Y \epsilon_y^r+Yln\sigma_r\rangle$                          | Recruitment deviation penalty                                                                             | $\sigma_r$ recruitment variability                                                              | 1                                   |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
| $\lambda_{F}\sum_y \epsilon_y^f$                                                                        | Fishing mortality deviation penalty                                                                       |                                                                                                 | 0.1                                 |
+---------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------+
