---
params: 
  chapter: 10
  species: "Pacific Ocean Perch"
  species_complex: "no"
  area: "Gulf of Alaska"
  tier: 3
author: "Maia S. Kapur, Peter-John F. Hulson, Ben Williams"
date: "November 2023"

# don't do anything below this line unless you are cool with the consequences
output:
  bookdown::word_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: false
     css: "styles.css"
     pandoc_args:  
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in     
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

---


```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
knitr::opts_knit$set(eval.after = "fig.cap")
x = 1
sprintf("Figure %s. " , paste0(params$chapter, '.',x))
```

```{r}
if(params$species_complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock Complex in the ", params$area)  
  }


```

---
title: `r title`
---

```{r load, warning=F, message=F}
# load
library(safe)
library(here)
# globals
species = params$species
year = 2023
date = 'October 22, 2023'
model = '2020.1-2023'
end_proj = year + 15
best_f = 0.0641 # from the best_f function in groundfishr package
ofl = 8000 # placeholder while i figure things out
abc_22 <- 38268; abc_22p <- prettyNum(abc_22,big.mark=',')
abc_23 <- 1.06*abc_22 
abc<-prettyNum(round(abc_23,1),big.mark=',')
# todo: read from proj output
c1 = 2842 # estimated catch in current year
c2 = 3489 # proj catch year + 1
c3 = 2884 # proj catch year + 2
# todo: build a function/switch to auto run the tier(a/b) - also for overfishing/overfished

## load in derived quants & model results
mdlres <- list.files(here(year,'mgmt','2020.1-2023','processed'), pattern = '.csv', full.names = TRUE)
for(i in 1:length(mdlres)){
  assign(x = gsub('.csv','',basename(mdlres[i])), value = read.csv(mdlres[i]))
}
```
 
```{r, child="01-summary.Rmd", eval = T}
```

```{r, child="02-responses.Rmd", eval = T}
```

```{r, child="03-intro-update.Rmd", eval = T}
```

```{r, child="04-fishery-update.Rmd", eval = T}
```

```{r, child="05-data-update.Rmd", eval = T}
```

```{r, child="06-model-update.Rmd", eval = T}
```

```{r, child="07-results-update.Rmd", eval = T}
```

```{r, child="08-abc.Rmd", eval = T}
```

```{r, child="09-ecosystem.Rmd", eval = T}
```

```{r, child="10-gaps.Rmd", eval = T}
```
\pagebreak
\allsectionsfont{\centering}
# References
<div id="refs"></div>

```{r, child="11a-auxiliaryfiles.Rmd", eval = T}
```

```{r, child="11-tables-update.Rmd", eval = T}
```

```{r, child="12-figures-update.Rmd", eval = T}
```

```{r, child="13-append_a.Rmd", eval = T}
```

```{r, child="14-append_vast.Rmd", eval = T}
```

```{r, child="15-append_cie.Rmd", eval = T}
```

```{r, child="16-append_eqs.Rmd", eval = T}
```


