# Introduction
## Biology and Distribution
Pacific ocean perch (*Sebastes alutus*, POP) have a wide distribution in the North Pacific from southern California around the Pacific rim to northern Honshu Is., Japan, including the Bering Sea. The species appears to be most abundant in northern British Columbia, the Gulf of Alaska (GOA), and the Aleutian Islands (Allen and Smith 1988). Adults are found primarily offshore on the outer continental shelf and the upper continental slope in depths of 150-420 m. Seasonal differences in depth distribution have been noted by many investigators. In the summer, adults inhabit shallower depths, especially those between 150 and 300 m. In the fall, the fish apparently migrate farther offshore to depths of ~300-420 m. They reside in these deeper depths until about May, when they return to their shallower summer distribution (Love et al. 2002). This seasonal pattern is probably related to summer feeding and winter spawning. Although small numbers of POP are dispersed throughout their preferred depth range on the continental shelf and slope, most of the population occurs in patchy, localized aggregations (Hanselman et al. 2001). POP are generally considered to be semi-demersal but there can at times be a significant pelagic component to their distribution. POP often move off-bottom during the day to feed, apparently following diel euphausiid migrations (Brodeur 2001). Commercial fishing data in the GOA since 1995 show that pelagic trawls fished off-bottom have accounted for as much as 31% of the annual harvest of this species.

There is much uncertainty about the life history of POP, although generally more is known than for other rockfish species (Kendall and Lenarz 1986). The species appears to be viviparous (the eggs develop internally and receive at least some nourishment from the mother), with internal fertilization and the release of live young. Insemination occurs in the fall, and sperm are retained within the female until fertilization takes place ~2 months later. The eggs hatch internally, and parturition (release of larvae) occurs in April-May. Information on early life history is very sparse, especially for the first year of life. POP larvae are thought to be pelagic and drift with the current, and oceanic conditions may sometimes cause advection to suboptimal areas (Ainley et al. 1993) resulting in high recruitment variability. However, larval studies of rockfish have been hindered by difficulties in species identification since many larval rockfish species share the same morphological characteristics (Kendall 2000). Genetic techniques using allozymes (Seeb and Kendall 1991) and mitochondrial DNA (Li 2004) are capable of identifying larvae and juveniles to species, but are expensive and time-consuming. Post-larval and early young-of-the-year POP have been positively identified in offshore, surface waters of the GOA (Gharrett et al. 2002), which suggests this may be the preferred habitat of this life stage. Transformation to a demersal existence may take place within the first year (Carlson and Haight 1976). Small juveniles probably reside inshore in very rocky, high relief areas, and by age 3 begin to migrate to deeper offshore waters of the continental shelf (Carlson and Straty 1981). As they grow, they continue to migrate deeper, eventually reaching the continental slope where they attain adulthood. Adult and juvenile populations are believed to be spatially separated (Carlson and Straty 1981; Rooper et al. 2007). 

POP are mostly planktivorous (Carlson and Haight 1976; Yang 1993; Yang and Nelson 2000; Yang 2003; Yang et al. 2006). In a sample of 600 juvenile perch stomachs, Carlson and Haight (1976) found that juveniles fed on an equal mix of calanoid copepods and euphausiids. Larger juveniles and adults fed primarily on euphausiids, and to a lesser degree, copepods, amphipods and mysids (Yang and Nelson 2000). In the Aleutian Islands, myctophids have increasingly comprised a substantial portion of the POP diet, which also compete for euphausiid prey (Yang 2003). POP and walleye pollock (Gadus chalcogrammus) probably compete for the same euphausiid prey as euphausiids make up about 50% of the pollock diet (Yang and Nelson 2000). Consequently, the large removals of POP by foreign fishermen in the GOA in the 1960s may have allowed walleye pollock stocks to greatly expand in abundance.

Predators of adult POP are likely sablefish, Pacific halibut, and sperm whales (Major and Shippen 1970). Juveniles are consumed by seabirds (Ainley et al. 1993), other rockfish (Hobson et al. 2001), salmon, lingcod, and other large demersal fish.
POP is a slow growing species, with a low rate of natural mortality, a relatively old age at 50% maturity (8.4 - 10.5 years for females in the GOA), and a very old maximum age of 98 years in Alaska (84 years maximum age in the GOA) (Hanselman et al. 2003a). Age at 50% recruitment to the commercial fishery has been estimated to be between 7 and 8 years in the GOA. Despite their viviparous nature, they are relatively fecund with number of eggs/female in Alaska ranging from 10,000-300,000, depending upon size of the fish (Leaman 1991). Rockfish in general were found to be about half as fecund as warm water snappers with similar body shapes (Haldorson and Love 1991).

The evolutionary strategy of spreading reproductive output over many years is a way of ensuring some reproductive success through long periods of poor larval survival (Leaman and Beamish 1984). Fishing generally selectively removes the older and faster-growing portion of the population. If there is a distinct evolutionary advantage of retaining the oldest fish in the population, either because of higher fecundity or because of different spawning times, age-compression could be deleterious to a population with highly episodic recruitment like rockfish (Longhurst 2002). 

Research on black rockfish (Sebastes melanops) has shown that larval survival may be dramatically higher from older female spawners (Berkeley et al. 2004, Bobko and Berkeley 2004). The black rockfish population has shown a distinct downward trend in age-structure in recent fishery samples off the West Coast of North America, raising concerns about whether these are general results for most rockfish. de Bruin et al. (2004) examined POP (S. alutus) and rougheye rockfish (S. aleutianus) for senescence in reproductive activity of older fish and found that oogenesis continues at advanced ages. Leaman (1991) showed that older individuals have slightly higher egg dry weight than their middle-aged counterparts. Such relationships have not yet been determined to exist for POP or other rockfish in Alaska. Stock assessments for Alaska groundfish have assumed that the reproductive success of mature fish is independent of age. Spencer et al. (2007) showed that the effects of enhanced larval survival from older mothers decreased estimated $F_{MSY}$ (the fishing rate that produces maximum sustainable yield) by 3% to 9%, and larger decreases in stock productivity were associated at higher fishing mortality rates that produced reduced age compositions. Preliminary work at Oregon State University examined POP of adult size by extruding larvae from harvested fish near Kodiak, and found no relationship between spawner age and larval quality (Heppell et al. 2009). However, older spawners tended to undergo parturition earlier in the spawning season than younger fish. A more recent study suggest that larval quality is both a function of spawner age and parturition timing.

## Stock Structure

A few studies have been conducted on the stock structure of POP. Based on allozyme variation, Seeb and Gunderson (1988) concluded that POP are genetically quite similar throughout their range, and genetic exchange may be the result of dispersion at early life stages. In contrast, analysis using mitochondrial DNA techniques indicates that genetically distinct populations of POP exist (Palof 2008). Palof et al. (2011) report that there is low, but significant genetic divergence (FST = 0.0123) and there is a significant isolation by distance pattern. They also suggest that there is a population break near the Yakutat area from conducting a principle component analysis. Withler et al. (2001) found distinct genetic populations on a small scale in British Columbia. Kamin et al. (2013) examined genetic stock structure of young of the year POP. The geographic genetic pattern they found was nearly identical to that observed in the adults by Palof et al. (2011).
In a study on localized depletion of Alaskan rockfish, Hanselman et al. (2007) showed that POP are sometimes highly depleted in areas 5,000-10,000 km2 in size, but a similar amount of fish return in the following year. This result suggests that there is enough movement on an annual basis to prevent serial depletion and deleterious effects on stock structure. In 2012, the POP assessment presented the completed stock structure template that summarized the body of knowledge on stock structure and spatial management (Hanselman et al. 2012a). 

