---
editor_options: 
  markdown: 
    wrap: sentence
---

# Data

> Operational Update: The data description for POP has been truncated to highlight relevant updates or changes made for this cycle. The reader is referred to the last full assessment (Hulson et al., 2021) for the entirety of this section.

The following table summarizes the data used for this assessment (bold font denotes new data to this year's assessment):

```{r}

data.frame(Source = c(rep("NMFS Groundfish survey", 2),
                      rep("U.S. trawl fishery", 3)),
           Data = c("Survey biomass",
                    "Age composition",
                    "Catch",
                    "Age composition",
                    "Length composition"),
           Years = c("1984-1999 (triennial), 2001-2019 (biennial)",
                     "1984, 1987, 1990, 1993, 1996, 1999, 2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017, 2019",
                     "1961-2020",
                     "1998-2002, 2004-2006, 2008, 2010, 2012, 2014, 2016, 2018",
                     "1991-1997, 2003, 2007, 2009, 2011, 2013, 2015, 2017, 2019"))  %>% 
  flextable::flextable() %>% 
    flextable::width(j = ~ Source, width = 1) %>% 
    flextable::width(j = ~ Data, width = 1.5) %>% 
   flextable::width(j = ~ Years, width = 4) %>% 
   flextable::merge_v(j = 1) %>% 
  flextable::font(fontname = "Times", part = "all") %>% 
  flextable::fontsize(size = 10) %>% 
  flextable::theme_vanilla() %>% 
  flextable::fix_border_issues() 

```

## Summer Acoustic-Trawl Survey

Acoustic-trawl (AT) surveys designed to evaluate walleye pollock abundance in the Gulf of Alaska have been conducted by the Alaska Fisheries Science Center (AFSC) in summer months (June -- August) on odd years from 2013 to 2021 aboard the NOAA ship Oscar Dyson (Jones et al. 2014, Jones et al. 2017, Jones et al. 2019). POP are routinely encountered during these surveys and abundance estimates for POP are available for the surveyed area.
 
The following table includes the biomass estimates provided by the AT survey; these are *not* used in the assessment model.

| Year         | 2013      | 2015     | 2017     | 2019     | 2021    |
|--------------|-----------|----------|----------|----------|---------|
| Biomass (mt) |  262,889  | 438,545  | 172,388  | 144,045  | 277,941 |
 
 
