# Ecosystem Considerations

In general, a determination of ecosystem considerations for POP is hampered by the lack of biological and habitat information. A summary of the ecosystem considerations presented in this section is listed in Table 9-20.

## Ecosystem Effects on the Stock

**Prey availability/abundance trends**: Similar to many other rockfish species, stock condition of POP appears to be influenced by periodic abundant year classes. Availability of suitable zooplankton prey items in sufficient quantity for larval or post-larval POP may be an important determining factor of year class strength. Unfortunately, there is no information on the food habits of larval or post-larval rockfish to help determine possible relationships between prey availability and year class strength; moreover, identification to the species level for field collected larval slope rockfish is difficult. Visual identification is not possible though genetic techniques allow identification to species level for larval slope rockfish (Gharrett et. al 2001). Some juvenile rockfish found in inshore habitat feed on shrimp, amphipods, and other crustaceans, as well as some mollusk and fish (Byerly 2001). Adult POP feed primarily on euphausiids. Little if anything is known about abundance trends of likely rockfish prey items. Euphausiids are also a major item in the diet of walleye pollock. Recent declines in the biomass of walleye pollock, could lead to a corollary change in the availability of euphausiids, which would then have a positive impact on POP abundance.

**Predator population trends**:  POP are preyed upon by a variety of other fish at all life stages, and to some extent marine mammals during late juvenile and adult stages. Whether the impact of any particular predator is significant or dominant is unknown. Predator effects would likely be more important on larval, post-larval, and small juvenile slope rockfish, but information on these life stages and their predators is scarce.

**Changes in physical environment**: Stronger year classes corresponding to the period around 1977 have been reported for many species of groundfish in the GOA, including POP, northern rockfish, sablefish, and Pacific cod. Therefore, it appears that environmental conditions may have changed during this period in such a way that survival of young-of-the-year fish increased for many groundfish species, including slope rockfish. POP appeared to have strong 1986-88 year classes, and there may be other years when environmental conditions were especially favorable for rockfish species. The environmental mechanism for this increased survival remains unknown. Changes in water temperature and currents could affect prey abundance and the survival of rockfish from the pelagic to demersal stage. Rockfish in early juvenile stage have been found in floating kelp patches which would be subject to ocean currents. Changes in bottom habitat due to natural or anthropogenic causes could alter survival rates by altering available shelter, prey, or other functions. Carlson and Straty (1981), Pearcy et al (1989), and Love et al (1991) have noted associations of juvenile rockfish with biotic and abiotic structure. Research by Rooper and Boldt (2005) found juvenile POP abundance was positively correlated with sponge and coral. 

The Essential Fish Habitat Environmental Impact Statement (EFH EIS) (NMFS 2005) concluded that the effects of commercial fishing on the habitat of groundfish is minimal or temporary. The continuing upward trend in abundance of POP suggests that at current abundance and exploitation levels, habitat effects from fishing are not limiting this stock.


## Fishery Effects on the Ecosystem 
**Fishery-specific contribution to bycatch of HAPC biota**: In the GOA, bottom trawl fisheries for pollock, deepwater flatfish, and POP account for most of the observed bycatch of coral, while rockfish fisheries account for little of the bycatch of sea anemones or of sea whips and sea pens. The bottom trawl fisheries for POP and Pacific cod and the pot fishery for Pacific cod account for most of the observed bycatch of sponges (Table 9-5). 

**Fishery-specific concentration of target catch in space and time relative to predator needs in space and time (if known) and relative to spawning components**:  The directed slope rockfish trawl fisheries used to begin in July, were concentrated in known areas of abundance, and typically lasted only a few weeks. The Rockfish Pilot project has spread the harvest throughout the year in the Central GOA. The recent annual exploitation rates on rockfish are thought to be quite low. Insemination is likely in the fall or winter, and parturition is likely mostly in the spring. Hence, reproductive activities are probably not directly affected by the commercial fishery. There is momentum for extending the rockfish fishery over a longer period, which could have minor effects on reproductive output.

**Fishery-specific effects on amount of large size target fish**: The proportion of older fish has increased in the trawl survey and the estimated selectivity for the fishery in recent years in dome-shaped, thus, the fishery seems to be having negligible impact on the amount of older fish in the population.
Fishery contribution to discards and offal production: Fishery discard rates for the whole rockfish trawl fishery since 2000 are on average 33% and have ranged from 27% to 43%. Arrowtooth flounder comprised 7-44% of these discards since 2000, and have been less than 20% since 2008. Non-target discards are summarized in Table 9-5, with grenadiers (Macrouridae sp.) dominating the non-target discards.

**Fishery-specific effects on age-at-maturity and fecundity of the target fishery**:  Research is under way to examine whether the loss of older fish is detrimental to spawning potential.

**Fishery-specific effects on EFH non-living substrate**: Effects on non-living substrate are unknown, but the heavy-duty “rockhopper” trawl gear commonly used in the fishery is suspected to move around rocks and boulders on the bottom. Table 9-5 shows the estimated bycatch of living structure such as benthic urochordates, corals, sponges, sea pens, and sea anemones by the GOA rockfish fisheries.  The average bycatch of corals/bryozoans and sponges by rockfish fisheries are a large proportion of the catch of those species taken by all Gulf-wide fisheries.

## GOA Rockfish Economic Performance Report for 2020 
Rockfish total catch in the Gulf of Alaska decreased 6% to 34 thousand t in 2020 relative to 2019 and retained catch decreased to 30.3 thousand t (Table 9-21). Catch remains near the recent highs over the last decade. Rockfish are an important component of the catch portfolio of GOA fisheries. Ex-vessel value in the GOA rockfish fisheries in 2020 was $9.5 million down 35% from 2019. The change in ex-vessel value was combined effect of marginal decreases in catch and 37% decrease in prices to $0.15 per pound (Table 9-21). First-wholesale value was down 13% in 2020 to $29.2 million with a significant decrease in the first-wholesale price (Table 9-22).

COVID-19 had an unprecedented impact on fisheries in Alaska. Undoubtedly, one of the significant economic impacts experienced by the industry were the mitigation costs experienced by the fishing and processing industries to continue to supply national and global markets for seafood. Existing data collections do not adequately capture these costs, and as such, this report focuses on catch, revenues, and effort and changes occurring during the most recent year. GOA rockfish catch levels relative to TAC were within a typical range suggesting that COVID-19 did not have a significant impact on catch levels. In contrast to changes in landings, however, there was a notable decrease in prices for many of the products with significant exports to China for reprocessing and Japan, which ultimately go to food service sectors. This includes GOA rockfish, which has significant end markets in Asia and North America in both foodservice and retail. The downward pressure on these prices is likely the result of COVID-19 related logistical difficulties in international shipping and inspections, as well as foodservice closures, and compounded the downward pressure on prices from tariffs. This downward pressure on fish product prices in the first-wholesale market coupled with cost pressure from COVID-19 mitigation efforts likely had upstream impacts on ex-vessel prices that decreased significantly.

The most significant species in terms of market volume and value is Pacific ocean perch which has accounted for upwards of 70% of the retained catch since 2017 (Table 9-21). Harvest levels of Pacific ocean perch are near the total allowable catch (TAC) and has been strong in recent years reflecting the underlying health of the stock. The GOA rockfish fisheries catch a diverse set of rockfish species and the other major species caught are northern and dusky (Table 9-21). Typically, 75%-90% of the northern rockfish TAC is harvested, and since 2017 this has dropped to roughly 60%. In 2019 retained catch of northern rockfish decreased to 2.4, and retained catch of Dusky rockfish decreased to 2.1 thousand t. Other rockfish caught in the GOA include rougheye, shortraker, and thornyhead. In recent years, approximately 85% of the retained rockfish catch has occurred in the Central Gulf. The Western Gulf’s share of retained catch was 12%. In the Central Gulf, where the majority of rockfish are caught, rockfish comprised 18% of the retained catch and 14% of the ex-vessel value, which is up relative to the years prior to 2017 in part because of reduced catch and value in other fisheries, in particular Pacific cod. Catch in the GOA is distributed approximately evenly between catcher vessels and catcher processors, although there are a far greater number of catch vessels. The number of catcher vessels harvesting rockfish has increase from an average of 178 in 2011-2015 to 182 in 2019, then dropped off to 157 in 2020. Rockfish are primarily targeted using trawl gear. 

The Central Gulf of Alaska rockfish fisheries are managed under a catch share program designed to reduce bycatch and discards and to improve quality and value. The Rockfish Program began in 2012 and followed a pilot program from 2007-2011. Quota is allocated to catcher vessel and catcher processor cooperatives. Catch shares have had the effect of spreading the production out over the year which enabled delivered product to be processed more strategically thereby increasing the quality of the product.

The 13% decrease in 2020 first-wholesale value to \$29 million was largely the result of a decrease in the first wholesale price (Table 9-22). The average price of rockfish products decreased 17% to $0.75 per pound. Prices for Pacific ocean perch, Northern, and Dusky decreased 16%, 24%, and 7%, respectively. Approximately 70% of the rockfish produced are processed as headed and gutted (H&G) which is lower than in most recent years as whole fish production increased whole fish. 

The majority of rockfish produced in the U.S. are exported, primarily to Asian markets. Pacific ocean perch is the only rockfish species with specific information in the U.S. trade data. Other species are aggregated into a non-specific category. While export volumes were relatively stable, increasing 5%, there was a minor shift in product flow in 2020 relative to 2019. Approximately 53% of the Pacific ocean perch export value from the U.S. went to China in 2020 which was a decrease relative 2019, but not inconsistent with recent trade levels (e.g., 2015, 2017) (Table 9-23). Japan is the second largest export destination for Pacific ocean perch. Exported H&G rockfish to China is re-processed (e.g., as fillets) and re-exported to domestic and international markets. Rockfish are also sold to Chinese consumers, as whole fish. The U.S. has accounted for just over 15% of global Pacific ocean perch production in recent years and 85-95% of global production. Global production of rockfish has increased 16% from the 2011-2015 average to 329 thousand t in 2019 and global production of Pacific ocean perch has increased 37%. Global production of Atlantic redfish, a market competitor to Pacific ocean perch, has been stable at 52 thousand t since 2017. The U.S. dollar weakened somewhat against the Chinese Yuan in 2020 but was within its historical range, which mitigates its potential impact on market price. Because of China’s significance as a re-processor of rockfish products, the tariffs between the U.S. and China, which begun in 2018, have put downward pressure on rockfish prices which has inhibited value growth in rockfish markets. Pacific ocean Perch was among the species to receive relief under the USDA Seafood Tariff Relief Program in 2019-2020. Industry lacks immediate alternative reprocessing options to China on a large scale. Export quantities of Pacific ocean perch increased in 2020 from 2019 and the share of exports to China decreased (Table 9-23). The COVID-19 pandemic created supply chain logistical difficulties, particularly in China, which put downward pressure on prices. The share of exports to Japan increased which mitigated the impact on value. In addition, foodservice closures in major markets for rockfish finished goods, also likely impacted prices negatively.

