\newpage

## Area Allocation of Catches

> The apportionment of catches for `r year+1` and `r year+2` was conducted using the REMA model using the same assumptions as in 2021. Details on the workflow to calculate apportionment are provided in @Kapur2023.

Because Amendment 41 prohibits trawling in the Eastern area east of 140° W longitude, the ABC allocation derived from REMA for the Eastern Gulf is split between W. Yakutat and E. Yakutat/Southeast Outside ('Southeast' or 'SEO') using a weighted average of area-specific biomass ratios obtained from the trawl survey. 
The OFL for the SEO region was previously separated from the remaining GOA areas because of concerns regarding stock structure differences in the SEO vs other areas. 
In 2023, the Plan Team and SSC recommended specifying OFL at the GOA-wide level to be consistent with stock status determination criteria and due to the lack of strong rationale of a biological basis for partitioning OFL separately in the SEO region. 

```{r echo = FALSE, eval = T, message=F}
## manually bind correct values
exec_summ <- vroom::vroom(here::here(year, folder, "processed", "exec_summ.csv"))
abc = as.numeric(exec_summ[13,4])
abc1 = as.numeric(exec_summ[13,5])
ofl = as.numeric(exec_summ[11,4])
ofl1 = as.numeric(exec_summ[11,5])

abc_appo = round(abc * abc_apport[1,3:5])
abc_appo1 = round(abc1 * abc_apport[1,3:5])
# gotta be the same sum - make sure rounding didn't misplace a ton
# abc - sum(abc_appo)
# abc1 - sum(abc_appo1)

# split egoa
wy = round(abc_apport_wyak$wyak_p[1] * abc_appo[1,'egoa']) 
wy1 = round(abc_apport_wyak$wyak_p[1] * abc_appo1[1,'egoa'])
seo = abc_appo[1,'egoa'] - wy
seo1 = abc_appo1[1,'egoa'] - wy1

# gotta sum the same
# abc_appo$egoa - (wy + seo) 
# abc_appo1$egoa - (wy1 + seo1) 

# all looks good? then make a table
abc_appo %>% 
  dplyr::mutate(wyak = wy,
                seo = seo) %>% 
    add_row() %>% 
    dplyr::mutate(year = as.character(rep(year+1, 2)),
                  item = c('ABC (t)', 'OFL (t)'),
                  total = c(abc, ofl)) %>% 
  bind_rows(
abc_appo1 %>% 
  dplyr::mutate(wyak = wy1,
                seo = seo1) %>% 
    add_row() %>% 
    dplyr::mutate(year = as.character(rep(year+2, 2)),
                  item = c('ABC (t)', 'OFL (t)'),
                  total = c(abc1, ofl1))) %>% 
  dplyr::select(year, item, wgoa, cgoa, wyak, seo, total) -> appo

# in theory this self updates - though doublecheck the rounding addition
flextable::flextable(appo) %>% 
    flextable::add_header_row(values = paste0(c('REMA-derived apportionment (%)', 
                                              100*abc_apport[1,'wgoa'],
                                              100*abc_apport[1,'cgoa'],
                                              100*abc_apport[1,'egoa'],
                                              100*abc_apport[1,'goa'])), 
                            colwidths = c(2,1,1,2,1)) %>% 
    flextable::set_header_labels(values = c('Year','Quantity','Western','Central','W. Yakutat','E. Yakutat/SEO','Total')) %>% 
  flextable::align(i=1:2, j=3:6, align='center', part='header') %>% 
  flextable::border_remove() %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
    flextable::fontsize(size = 11, part = "all") %>% 
    flextable::align(j = 1, part = "all", align="left") %>% 
    flextable::hline_top(part='all') %>% 
    flextable::vline(j = c(4,6), part = 'header') %>% 
    flextable::hline_bottom() 


```
