## Responses to SSC and Plan Team Comments on Assessments in General

>*1. With regard to the Joint Groundfish Plan Team (JGPT) suggestion that the AFSC consider producing the harvest projections for review at the September Plan Team meeting, the SSC is generally supportive of this suggestion, if the AFSC believes it to be feasible, as there are obvious benefits to the assessment teams. (JPT/SSC 2023)*

This harvest projection was produced prior to the September Plan Team meeting, as such the harvest expansion factor through the end of the year is noticeably increased from the previous assessment.

>*2. The SSC suggests that the previous full assessment links be provided in the harvest projections and catch reports to facilitate review. (JPT/SSC 2023)*

A link to the last operational full assessment is provided within.

## Responses to SSC and Plan Team Comments Specific to this Assessment. 

>*1. The SSC supports the GOA GPT recommendation to specify the OFL at the GOA-wide level to reflect the stock area.*

The OFL is reported at the GOA-wide level in this assessment. 

>*2. As the research on genetic structure of stocks proceeds, information on stock structure, or lack of it, for GOA POP should be updated.*

To be addressed in the next full assessment.

>*3. The SSC notes that comparing retrospective patterns across rockfish species may provide insight on common drivers (see the General Stock Assessment Comments).*

To be addressed in the next full assessment.

>*4. The SSC appreciates the work being done to address earlier GOA GPT, SSC and CIE comments. Please carry forward how all of these comments are being, or have been, addressed into the next full assessment report.*

The status of work addressing previous GOA GPT, SSC, and CIE comments (provided below) that were not addressed in the last full assessment [@Kapur2023] will be addressed in the next full assessment.

>*a. Re-evaluation of the age-plus group, as changes to the model and input data have occurred since this was previously evaluated (Plan Team, November 2018; CIE, 2021)*

>*b. Continued evaluation of methods for weighting for the compositional data as new models are developed and/or changes are made to input data. (Plan Team, November 2018)*

>*c. Investigation of natural mortality, as the current estimate of 0.066 is higher than the expected value from the prior distribution (0.05) and the prior may be constraining the model. (Plan Team, November 2018; SSC, December 2020; CIE, 2021)*

>*d. Incorporation of hydroacoustic information into the assessment as the species are regularly found throughout the water column. Exploration of using the raw acoustic survey lengths, the acoustic abundance weighted length compositions, or using the bottom trawl survey selectivity as a proxy. (SSC, December 2018; September 2019; Plan Team, November 2020; SSC, December 2020)*

>*e. Re-examination of fishery-dependent information, e.g., how age samples are being collected. (SSC, December 2018; SSC, December 2020)*

>*f. Examination of catchability, which has been an ongoing issue for POP and other rockfish species, coupled with selectivity (SSC, December 2018; Plan Team, November 2019; SSC, December 2019; SSC, December 2020)*

>*g. Evaluate the impacts of using a VAST model for POP abundance and/or apportionment. (SSC, December 2018; Plan Team, November 2019; SSC, December 2019)*	

 
 
 


 