---
params: 
  chapter: 9
  species: "Pacific Ocean Perch"
  species_complex: "no"
  area: "Gulf of Alaska"
  tier: 3
author: " Benjamin C. Williams, Maia S. Kapur and Peter-John F. Hulson,"
date: "November 2024"

# don't do anything below this line unless you are cool with the consequences
output:
  bookdown::html_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: false
     css: "styles.css"
     pandoc_args:  
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in     
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

---

```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
knitr::opts_knit$set(eval.after = "fig.cap")
x = 1
sprintf("Figure %s. " , paste0(params$chapter, '.',x))
```

```{r}
if(params$species_complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock Complex in the ", params$area)  
  }


```

---
title: `r title`
---

```{r load, warning=F, message=F, echo = FALSE}
# load
library(safe)
library(officedown)
library(here)
library(dplyr)
# globals
folder = "update"
species = params$species
year = yr = 2024
data_pull = read.table(here::here(year, "data", "raw", "data_called.txt"))[2,1]
data_pull2 = paste(months(as.Date(data_pull)), 
                    format(as.Date(data_pull,format="%Y-%m-%d"), format = "%d"))
catch = vroom::vroom(here::here(year, "data", "output", "fsh_catch.csv"))
yld = vroom::vroom(here::here(year, "data", "output", "yld_rat.csv"))
prj = readLines(here::here(year, folder, "proj", "model", "data", "pop_spcat.dat"))

c0 = safe::comma(dplyr::filter(catch, year==yr-1)$catch)
c1 = safe::comma(round(yld$proj_catch)) # estimated catch in current year
c2 = safe::comma(stringr::str_sub(prj[grep(year+1, prj)], 6, 10)) # proj catch year + 1
c3 = safe::comma(stringr::str_sub(prj[grep(year+2, prj)], 6, 10)) # proj catch yera + 2

exec_summ <- vroom::vroom(here::here(year, folder, "processed", "exec_summ.csv"))

tier = exec_summ[2,4]
tot = safe::comma(exec_summ[3,4])

ofl = safe::comma(exec_summ[11,4])
ofl0 = safe::comma(exec_summ[11,3])
sb1 = safe::comma(exec_summ[4,4])
sb2 = safe::comma(exec_summ[4,5])
b35 = safe::comma(exec_summ[7,4])
b40 = safe::comma(exec_summ[6,4])
b100 = safe::comma(exec_summ[5,4])

f40 = exec_summ[8,4]
f35 = exec_summ[10,4]

# bring in as numeric
abc = as.numeric(exec_summ[13,4])
abc0 = as.numeric(exec_summ[13,2])
abc01 = as.numeric(exec_summ[13,3])

# calculate percents
perc = round((abc-abc0)/abc0 * 100)
perc1 = round((abc-abc01)/abc01 * 100)

# change to text

abc = comma(abc)
abc0 = comma(abc0)
```

This report may be cited as:
Williams, B.C., M.S. Kapur, and P-J F. Hulson, 2024. Assessment of the Pacific Ocean Perch Stock in the Gulf of Alaska. North Pacific Fishery Management Council, Anchorage, AK. Available from https://www.npfmc.org/library/safe-reports/
  
  
```{r, child="01-summary.Rmd", eval = T}
```

```{r, child="02-responses.Rmd", eval = T}
```
\pagebreak
\allsectionsfont{\centering}
# References
<div id="refs"></div>


```{r, child="12-figures.Rmd", eval = T}
```
